/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/clients` | `/clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/clients` | `/clients`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/sessions` | `/sessions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(client)'}/sessions` | `/sessions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/clients${`?${string}` | `#${string}` | ''}` | `/clients${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/sessions${`?${string}` | `#${string}` | ''}` | `/sessions${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(client)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(client)'}/sessions${`?${string}` | `#${string}` | ''}` | `/sessions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/clients` | `/clients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(client)'}/sessions` | `/sessions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
